spring:

 rabbitmq:
   listener:
     default-requeue-rejected: false
     retry:
         enabled: true
         initial-interval: 5000
         max-attempts: 3
         multiplier: 1.5
         max-interval: 10000
   host: localhost
   port: 5672
   username: guest
   password: guest

 datasource:
   url: jdbc:h2:mem:bookings
   driverClassName: org.h2.Driver
   username: sa
   password: sa
 jpa:
   properties:
     javax:
       persistence:
         validation:
           mode: none




